/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GrocerAdminRole;

//import Business.Customer.CustomerDirectory;
import Business.Person.PersonDirectory;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Grocer.GrocerDirectory;
import Business.GroceryMenu.GMenuDirectory;
import Business.GroceryOrder.GOrderDirectory;
import Business.Network.Network;
import Business.Org.GroceryOrganization;
import Business.Org.Org;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author 16178
 */
public class GrocerAdminAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminAreaJPanel
     */
    JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem ecoSystem;
    private Network network;
    private Enterprise enterprise;
    private GroceryOrganization groceryOrganization;
    private PersonDirectory personDirectory;
    private GrocerDirectory grocerDirectory;
    private DeliveryManDirectory deliveryManDirectory;
    private GMenuDirectory gmenuDirectory;
    private GOrderDirectory gorderDirectory;
    
    public GrocerAdminAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecoSystem, Org organisation,Enterprise enterprise,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.ecoSystem = ecoSystem;
        this.groceryOrganization = (GroceryOrganization)organisation;
        this.network = network;
        this.enterprise = enterprise;
        this.personDirectory = ecoSystem.getPersonDirectory();
       this.grocerDirectory = ecoSystem.getGrocerDirectory();
        this.deliveryManDirectory = ecoSystem.getDeliverymanDirectory();
        this.gmenuDirectory = ecoSystem.getgMenuDirectory();
        this.gorderDirectory = ecoSystem.getgOrderDirectory();
        valueLabel.setText(account.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        storeButton = new javax.swing.JButton();
        manageMenuButton = new javax.swing.JButton();
        manageOrderButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Welcome, Grocer Admin!");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 53, 352, -1));

        storeButton.setBackground(new java.awt.Color(0, 102, 204));
        storeButton.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        storeButton.setForeground(new java.awt.Color(255, 255, 255));
        storeButton.setText("Manage Store Info");
        storeButton.setBorderPainted(false);
        storeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeButtonActionPerformed(evt);
            }
        });
        add(storeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 461, 263, 70));

        manageMenuButton.setBackground(new java.awt.Color(0, 102, 204));
        manageMenuButton.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        manageMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        manageMenuButton.setText("Manage Menu");
        manageMenuButton.setBorderPainted(false);
        manageMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMenuButtonActionPerformed(evt);
            }
        });
        add(manageMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 357, 263, 67));

        manageOrderButton.setBackground(new java.awt.Color(0, 102, 204));
        manageOrderButton.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        manageOrderButton.setForeground(new java.awt.Color(255, 255, 255));
        manageOrderButton.setText("Manage Orders");
        manageOrderButton.setBorderPainted(false);
        manageOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrderButtonActionPerformed(evt);
            }
        });
        add(manageOrderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 265, 263, 62));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(0, 102, 204));
        enterpriseLabel.setText("Store:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 188, 120, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 188, 130, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grocery_user-removebg-preview.png"))); // NOI18N
        jLabel7.setText("jLabel3");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 200, 320));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d1.png"))); // NOI18N
        jLabel8.setText("jLabel2");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 1710, 1000));
    }// </editor-fold>//GEN-END:initComponents

    private void storeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeButtonActionPerformed
        // TODO add your handling code here:
         ManageStoreInfoJPanel mrijp = new ManageStoreInfoJPanel(userProcessContainer,account, ecoSystem, grocerDirectory);
        userProcessContainer.add("manageRestJPanel",mrijp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
 

    }//GEN-LAST:event_storeButtonActionPerformed

    private void manageMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMenuButtonActionPerformed
    ManageMenuJPanel manageMenuJPanel = new ManageMenuJPanel(userProcessContainer,account, ecoSystem, grocerDirectory,gmenuDirectory);
        userProcessContainer.add("manageMenuJPanel",manageMenuJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageMenuButtonActionPerformed

    private void manageOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrderButtonActionPerformed

         ManageOrderJPanel manageOrderJPanel = new ManageOrderJPanel(userProcessContainer,account, ecoSystem, grocerDirectory,gmenuDirectory, gorderDirectory);
        userProcessContainer.add("ManageOrderJPanel",manageOrderJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrderButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton manageMenuButton;
    private javax.swing.JButton manageOrderButton;
    private javax.swing.JButton storeButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
