/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PharmacyAdminRole;

import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Grocer.GrocerDirectory;
import Business.GroceryMenu.GMenuDirectory;
import Business.GroceryOrder.GOrderDirectory;
import Business.Network.Network;
import Business.Org.Org;
import Business.Org.PharmacyOrganization;
import Business.Person.PersonDirectory;
import Business.Pharmacy.PharmacyDirectory;
import Business.PharmacyMenu.PMenuDirectory;
import Business.PharmacyOrder.POrderDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author 16178
 */
public class PharmaAdminAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminAreaJPanel
     */
    JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem ecoSystem;
    private Network network;
    private Enterprise enterprise;
    private PersonDirectory personDirectory;
    private PharmacyDirectory pharmacyDirectory;
    private DeliveryManDirectory deliveryManDirectory;
    private PMenuDirectory pmenuDirectory;
    private POrderDirectory porderDirectory;
    private PharmacyOrganization pharmacyOrganization;
    public PharmaAdminAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecoSystem, Org organisation,Enterprise enterprise,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.ecoSystem = ecoSystem;
        this.pharmacyOrganization = (PharmacyOrganization)organisation;
        this.network = network;
        this.enterprise = enterprise;
        valueLabel.setText(account.getUsername());
        this.personDirectory = ecoSystem.getPersonDirectory();
       this.pharmacyDirectory = ecoSystem.getPharmacyDirectory();
       this.deliveryManDirectory = ecoSystem.getDeliverymanDirectory();
        this.pmenuDirectory = ecoSystem.getpMenuDirectory();
        this.porderDirectory = ecoSystem.getpOrderDirectory();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        storeButton = new javax.swing.JButton();
        manageMenuButton = new javax.swing.JButton();
        manageOrderButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Welcome, Pharmacy Admin!");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 352, -1));

        storeButton.setBackground(new java.awt.Color(255, 255, 255));
        storeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        storeButton.setForeground(new java.awt.Color(0, 102, 204));
        storeButton.setText("Manage Store Info");
        storeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeButtonActionPerformed(evt);
            }
        });
        add(storeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 431, 280, 45));

        manageMenuButton.setBackground(new java.awt.Color(255, 255, 255));
        manageMenuButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manageMenuButton.setForeground(new java.awt.Color(0, 102, 204));
        manageMenuButton.setText("Manage menu");
        manageMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMenuButtonActionPerformed(evt);
            }
        });
        add(manageMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 341, 280, 49));

        manageOrderButton.setBackground(new java.awt.Color(255, 255, 255));
        manageOrderButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manageOrderButton.setForeground(new java.awt.Color(0, 102, 204));
        manageOrderButton.setText("Manage Orders");
        manageOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrderButtonActionPerformed(evt);
            }
        });
        add(manageOrderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 259, 280, 44));

        enterpriseLabel.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(0, 102, 204));
        enterpriseLabel.setText("Store:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 188, 120, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 130, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manage_pharm-removebg-preview.png"))); // NOI18N
        jLabel7.setText("jLabel3");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 500, 430));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d1.png"))); // NOI18N
        jLabel8.setText("jLabel2");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1710, 1000));
    }// </editor-fold>//GEN-END:initComponents

    private void storeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeButtonActionPerformed
        // TODO add your handling code here:
        ManageStoreInfoJPanel mrijp = new ManageStoreInfoJPanel(userProcessContainer,account, ecoSystem, pharmacyDirectory);
        userProcessContainer.add("manageRestJPanel",mrijp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_storeButtonActionPerformed

    private void manageMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMenuButtonActionPerformed
        ManageMenuJPanel manageMenuJPanel = new ManageMenuJPanel(userProcessContainer,account, ecoSystem, pharmacyDirectory,pmenuDirectory);
        userProcessContainer.add("manageMenuJPanel",manageMenuJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageMenuButtonActionPerformed

    private void manageOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrderButtonActionPerformed

        ManageOrderJPanel manageOrderJPanel = new ManageOrderJPanel(userProcessContainer,account, ecoSystem, pharmacyDirectory,pmenuDirectory, porderDirectory);
        userProcessContainer.add("ManageOrderJPanel",manageOrderJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrderButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton manageMenuButton;
    private javax.swing.JButton manageOrderButton;
    private javax.swing.JButton storeButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
