/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PersonRole;

//import Business.Customer.Customer;
import Business.Driver.Driver;
import Business.Driver.DriverDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Org.Org;
import Business.Org.PersonOrganization;
import Business.Person.Person;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DriverWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import javamailapp.javamail.JavaMailSystem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author grees
 */
public class CabJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CabJPanel
     */
    private JPanel userProcessContainer;
private EcoSystem ecoSystem;
private UserAccount account;
private DriverWorkRequest dreq;
private Enterprise ent;
private PersonOrganization organization;
private Network network;
public CabJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecoSystem,DriverWorkRequest dreq,Enterprise ent,Network network,PersonOrganization organization) {
initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.ecoSystem = ecoSystem;
        this.dreq = dreq;
        this.organization = organization;
        this.ent = ent;
        this.network = network;
        populateSeatsCombo();
        populateRequestTable();
    }
    
     public void populateSeatsCombo() {
        selectComboBox.removeAllItems();
        //selectComboBox.addItem(" ");
        
        for(Driver res : ecoSystem.getDriverDirectory().getDriverDirectory()) {
            System.out.println("res" + res);
            
            //selectComboBox.addItem(Integer.parseInt(res.getSeats())); String.valueOf(i)
            selectComboBox.addItem(String.valueOf(res.getSeats()));
           
        }
    }
     
      public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        //for (Gene g : ((LabTestWorkRequest) request).getPatient().getGeneHistory().getGeneHistory()) {
        for (WorkRequest request : account.getWorkQueue().getWorkRequestList()){
        if (request instanceof DriverWorkRequest) {
        //DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        // if(account.getEmployee().getName().equals(((DriverWorkRequest) dreq).getPerson().getName())) {
        Object[] row = new Object[5];
        row[0] = ((DriverWorkRequest) request).getPerson().getName();
        row[1] = ((DriverWorkRequest) request).getDestin();
        row[2] =((DriverWorkRequest) request).getDate();
        row[3] = ((DriverWorkRequest) request).getTime();
        row[4] = ((DriverWorkRequest) request);
        model.addRow(row);
//}
}
        
       /* for (DriverWorkRequest order : this.ecoSystem.getDriverDirectory().getDriverDirectory()){
            System.out.println("Order" + order.getOrderId());
            if(account.getEmployee().getName().equals(order.getCustomer().getName())) {
                Object[] row = new Object[7];
        
        DriverWorkRequest order = (DriverWorkRequest)jTable1.getValueAt(selectedRow, 0);
        order.setMessage(EDText.getText());
         populateRequestTable();*/
       }
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bookButton = new javax.swing.JButton();
        EDText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        selectComboBox = new javax.swing.JComboBox<>();
        dateTimePicker1 = new com.github.lgooddatepicker.components.DateTimePicker();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Time");
        jLabel5.setBackground(new java.awt.Color(0, 102, 204));
        jLabel5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, -1, -1));

        jLabel1.setText("Book a Cab");
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        backButton.setText("<< BACK");
        backButton.setBackground(new java.awt.Color(247, 247, 247));
        backButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backButton.setBorderPainted(false);
        backButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 102, 204));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 80, 30));

        jLabel3.setText("Destination:");
        jLabel3.setBackground(new java.awt.Color(0, 102, 204));
        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        jLabel4.setText("Date");
        jLabel4.setBackground(new java.awt.Color(0, 102, 204));
        jLabel4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 62, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "To", "Date", "Time", "Status"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionForeground(new java.awt.Color(102, 204, 255));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 545, 132));

        bookButton.setText("Book");
        bookButton.setBackground(new java.awt.Color(0, 102, 204));
        bookButton.setBorderPainted(false);
        bookButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bookButton.setForeground(new java.awt.Color(255, 255, 255));
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });
        add(bookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, -1, -1));

        EDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDTextActionPerformed(evt);
            }
        });
        add(EDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 201, -1));

        jLabel6.setText("Seats:");
        jLabel6.setBackground(new java.awt.Color(0, 102, 204));
        jLabel6.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        selectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Seats" }));
        selectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectComboBoxActionPerformed(evt);
            }
        });
        add(selectComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 130, -1));
        add(dateTimePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/taxi_ser.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBackground(new java.awt.Color(0, 102, 204));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, -10, 610, 280));
    }// </editor-fold>//GEN-END:initComponents

    private void EDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EDTextActionPerformed

    private void selectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectComboBoxActionPerformed

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        // TODO add your handling code here:
      // DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
       //System.out.println(LocalDate.now().format(formatter));
      LocalDate dt = LocalDate.from(ZonedDateTime.now());
        System.out.println(dt);
       
         if(EDText.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null,"Please enter destination address", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }
         
         if (dateTimePicker1.datePicker.getDate() == null || dateTimePicker1.timePicker.getTime() == null || dt.compareTo(dateTimePicker1.datePicker.getDate()) > 0 )
         {
             JOptionPane.showMessageDialog(null,"Please pick valid date and time", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
         }
         
      /*   if (dt.compareTo(dateTimePicker1.datePicker.getDate()) < 0 )
         {
             JOptionPane.showMessageDialog(null,"Please pick date and time", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
         }*/
         
        // if (dateTimePicker1.datePicker.getDate().compareTo(LocalDate.now().format(formatter)))
         
         System.out.println(dateTimePicker1.datePicker.getDate());
        // System.out.println(objSDF.format(objDate));
        String destin = EDText.getText();
        Person person = ecoSystem.getPersonDirectory().getPerson(account.getEmployee().getName());
        //String customer = ((DriverWorkRequest) dreq).getPerson().getName();
        //Person address = ecoSystem.getPersonDirectory().getPerson(account.getEmployee().getAddress());
         String seats = selectComboBox.getSelectedItem().toString();
        LocalDate date = dateTimePicker1.getDatePicker().getDate();
        LocalTime time = dateTimePicker1.getTimePicker().getTime();
        String status = "Cab Requested";
        DriverWorkRequest dreq = new DriverWorkRequest();
        dreq.setSeats(seats);
        dreq.setPerson(person);
        dreq.setDestin(destin);
        dreq.setDate(date);
        dreq.setTime(time);
        dreq.setDstatus(status);

        account.getWorkQueue().getWorkRequestList().add(dreq);
        ecoSystem.getWorkQueue().getWorkRequestList().add(dreq);

        JOptionPane.showMessageDialog(null,"You have successfully requested a cab. Please wait for the driver to accept");
        populateRequestTable();
        try {
                JavaMailSystem.sendMail("kashyapdatta@gmail.com","Cab Requested","You have successfully requested for a cab on"+" " +date+" "+ "at"+" "+ time +" "+ "to"+" "+ destin+" "+"Please wait for the doctor to accept it");
           } catch (Exception ex) {
               //Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
          }
        try {
                JavaMailSystem.sendMail("kashyapdatta@gmail.com","New Appointment Request","You have been requested for an cab on"+" " +date+" "+"at"+" "+ time +" "+ "to"+" "+ destin+" "+ "Please login to the app to accept the ride");
           } catch (Exception ex) {
               //Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
          }
        }
    
    private void backkButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        

         
    }//GEN-LAST:event_bookButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
               userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PersonAreaJPanel a = (PersonAreaJPanel) component;
        //a.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EDText;
    private javax.swing.JButton backButton;
    private javax.swing.JButton bookButton;
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePicker1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> selectComboBox;
    // End of variables declaration//GEN-END:variables
}
