/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PersonRole;

import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Grocer.Grocer;
import Business.Grocer.GrocerDirectory;
import Business.GroceryMenu.GMenu;
import Business.GroceryMenu.GMenuDirectory;
import Business.GroceryOrder.GOrder;
import Business.GroceryOrder.GOrderDirectory;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.Pharmacy.Pharmacy;
import Business.PharmacyMenu.PMenu;
import Business.PharmacyOrder.POrder;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author grees
 */
public class GroceryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GroceryJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private UserAccount account;
    private PersonDirectory personDirectory;
    private GrocerDirectory grocerDirectory;
   
    private DeliveryManDirectory deliveryManDirectory;
    private GMenuDirectory gmenuDirectory;
    private GOrderDirectory gorderDirectory;
    private static int count = 1;
    public GroceryJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecoSystem, 
            PersonDirectory personDirectory, GrocerDirectory grocerDirectory, 
            DeliveryManDirectory deliveryManDirectory, GMenuDirectory gmenuDirectory, GOrderDirectory gorderDirectory) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.ecoSystem = ecoSystem;
        this.personDirectory = ecoSystem.getPersonDirectory();
        this.grocerDirectory = ecoSystem.getGrocerDirectory();
        this.gmenuDirectory = ecoSystem.getgMenuDirectory();
        this.deliveryManDirectory = ecoSystem.getDeliverymanDirectory();
        this.gorderDirectory = ecoSystem.getgOrderDirectory();
        //valueLabel.setText(account.getUsername());
        //populateRequestTable();
        populateRestaurantCombo();
        //valueLabel.setText(enterprise.getName());
        populateRequestTable();
    }
    
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        model.setRowCount(0);
       //SimpleDateFormat strDate = new SimpleDateFormat("MM/dd/yyyy");
       System.out.println("ecoSystem" + this.ecoSystem);
        for (GOrder order : this.ecoSystem.getgOrderDirectory().getOrderDirectory()){
            System.out.println("Order" + order.getOrderId());
            if(account.getEmployee().getName().equals(order.getPerson().getName())) {
                Object[] row = new Object[7];
                row[0] = order;
                row[1] = order.getMenu().getItemName();
                row[2] = order.getQuantity() * order.getMenu().getPrice();
                row[3] = order.getGrocer().getGrocerName();
                row[4] = order.getPerson().getName();
                row[5] = order.getOrderStatus();
                row[6] = order.getQuantity();
              //  row[7] = order.getTime().toString();
                model.addRow(row);
    }
        }
    }
    
      public void populateRestaurantCombo() {
        selectComboBox.removeAllItems();
        selectComboBox.addItem("  ");
        for(Grocer res : ecoSystem.getGrocerDirectory().getGrocerDirectory()) {
            System.out.println("res" + res);
            selectComboBox.addItem(res.getGrocerName());
        }
    }
      
       public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) jtable1.getModel();
        dtm.setRowCount(0);
        String grocername = selectComboBox.getSelectedItem().toString();
        Grocer grocer = ecoSystem.getGrocerDirectory().getGrocer(grocername);
        for(GMenu gmenu : ecoSystem.getgMenuDirectory().getGmenuDirectory()){
            if(grocer.getGrocerName().equals(gmenu.getGrocerName())) {
                Object [] row = new Object[2];
                row[0] = gmenu;
                row[1] = gmenu.getPrice();
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        QuanText = new javax.swing.JTextField();
        OrderButton = new javax.swing.JButton();
        enterpriseLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        selectComboBox = new javax.swing.JComboBox<>();
        MenuButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        BackButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Select Quantity");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 110, -1));
        add(QuanText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 89, -1));

        OrderButton.setBackground(new java.awt.Color(0, 102, 204));
        OrderButton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        OrderButton.setForeground(new java.awt.Color(255, 255, 255));
        OrderButton.setText("Place Order");
        OrderButton.setBorderPainted(false);
        OrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderButtonActionPerformed(evt);
            }
        });
        add(OrderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        enterpriseLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        enterpriseLabel2.setForeground(new java.awt.Color(0, 102, 204));
        enterpriseLabel2.setText("Order details:");
        add(enterpriseLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 150, 30));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Order");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 63, -1, -1));

        selectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Store" }));
        selectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectComboBoxActionPerformed(evt);
            }
        });
        add(selectComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 130, -1));

        MenuButton.setBackground(new java.awt.Color(0, 102, 204));
        MenuButton.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        MenuButton.setForeground(new java.awt.Color(255, 255, 255));
        MenuButton.setText("Display Menu");
        MenuButton.setBorderPainted(false);
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });
        add(MenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        jtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Items", "Price"
            }
        ));
        jScrollPane2.setViewportView(jtable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 218, 90));

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "ItemName", "Price", "Store", "Customer", "Status", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 469, 780, 91));

        BackButton.setBackground(new java.awt.Color(255, 255, 255));
        BackButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        BackButton.setForeground(new java.awt.Color(0, 102, 204));
        BackButton.setText("<< BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 607, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gro_usr-removebg-preview.png"))); // NOI18N
        jLabel7.setText("jLabel3");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 500, 470));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Select Store");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, 20));

        jLabel8.setBackground(new java.awt.Color(0, 102, 204));
        jLabel8.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d1.png"))); // NOI18N
        jLabel8.setText("jLabel2");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1710, 1000));
    }// </editor-fold>//GEN-END:initComponents

    private void selectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectComboBoxActionPerformed

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        // TODO add your handling code here:
         if(selectComboBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Please select a restaurant");
            return;
        }
        populateTable();

    }//GEN-LAST:event_MenuButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
           userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PersonAreaJPanel a = (PersonAreaJPanel) component;
        //a.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void OrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = jtable1.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(QuanText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Please enter quantity", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int quantity = Integer.parseInt(QuanText.getText());
        String grocerName = selectComboBox.getSelectedItem().toString();
        Grocer grocer = ecoSystem.getGrocerDirectory().getGrocer(grocerName);
        Person person = ecoSystem.getPersonDirectory().getPerson(account.getEmployee().getName());
        GMenu menu = (GMenu) jtable1.getValueAt(selectedRow, 0);
        String status = "Order Placed";
        int min = 100;  
        int max = 1000; 
        int orderIdGen = (int)(Math.random()*(max-min+1)+min);
        GOrder order = ecoSystem.getgOrderDirectory().newOrder();
        order.setPerson(person);
        order.setOrderId(String.valueOf(orderIdGen));
        order.setQuantity(quantity);
        order.setMenu(menu);
        order.setGrocer(grocer);
        order.setOrderStatus(status);
        order.setAllot(false);
        
        JOptionPane.showMessageDialog(null,"You have placed an order");
        populateRequestTable();
    }//GEN-LAST:event_OrderButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton MenuButton;
    private javax.swing.JButton OrderButton;
    private javax.swing.JTextField QuanText;
    private javax.swing.JLabel enterpriseLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtable1;
    private javax.swing.JComboBox<String> selectComboBox;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
