/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PersonRole;


import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Nurse.Nurse;
import Business.Nurse.NurseDirectory;
import Business.Org.PersonOrganization;
import Business.Person.Person;
import Business.UserAccount.UserAccount;

import Business.WorkQueue.NurseWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZonedDateTime;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author grees
 */
public class NursingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NursingJPanel
     */
      private JPanel userProcessContainer;
private EcoSystem ecoSystem;
private UserAccount account;
private NurseWorkRequest nreq;
private Enterprise ent;
private PersonOrganization organization;
private Network network;
    public NursingJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecoSystem,NurseWorkRequest nreq,Enterprise ent,Network network,PersonOrganization organization) {
initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.ecoSystem = ecoSystem;
        this.nreq = nreq;
        this.organization = organization;
        this.ent = ent;
        this.network = network;
        populateSeatsCombo();
        populateRequestTable();
        double price = 13.5;
         priceText.setText(String.valueOf(price));
    }

     public void populateSeatsCombo() {
        jComboBox1.removeAllItems();
        //jComboBox1.addItem(" ");
        
        for(Nurse res : ecoSystem.getNurseDirectory().getNurseDirectory()) {
            System.out.println("res" + res);
            
            jComboBox1.addItem(String.valueOf(res.getGender()));
            
            //selectComboBox.addItem(Integer.parseInt(res.getSeats())); String.valueOf(i)
            //jComboBox1.addItem(String.valueOf(res.getSeats()));
        }
    }
     
       public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        double price = 13.5;
        //for (Gene g : ((LabTestWorkRequest) request).getPatient().getGeneHistory().getGeneHistory()) {
        for (WorkRequest request : account.getWorkQueue().getWorkRequestList()){
        if (request instanceof NurseWorkRequest) {
        //DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        // if(account.getEmployee().getName().equals(((DriverWorkRequest) dreq).getPerson().getName())) {
        Object[] row = new Object[4];
        row[0] = ((NurseWorkRequest) request).getDate();
        row[1] = ((NurseWorkRequest) request).getPerson().getName();
        //System.out.println((int) ((NurseWorkRequest) request).getDays());
        //System.out.println( price);
        
        row[2] =(int) ((NurseWorkRequest) request).getDays() *  price;
        //order.getQuantity() * order.getMenu().getPrice()
        row[3] = ((NurseWorkRequest) request);
        model.addRow(row);
//}
}
        }
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EDText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        priceText = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bookButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDTextActionPerformed(evt);
            }
        });
        add(EDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 196, 121, -1));

        jLabel1.setText("Book a Nurse");
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 49, -1, -1));

        jLabel2.setText("Start Date");
        jLabel2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jLabel3.setText("No. of Days");
        jLabel3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 152, -1, -1));

        priceText.setText("<Price>");
        add(priceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, -1, -1));

        jLabel4.setText("Select Gender");
        jLabel4.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 152, -1, -1));

        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 195, 69, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Start Date", "Customer Name", "Price", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 545, 132));

        bookButton.setText("Book");
        bookButton.setBackground(new java.awt.Color(0, 102, 204));
        bookButton.setBorderPainted(false);
        bookButton.setForeground(new java.awt.Color(255, 255, 255));
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });
        add(bookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 302, -1, -1));

        jLabel5.setText("Price per day");
        jLabel5.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, -1, -1));

        backButton.setText("<< BACK");
        backButton.setBackground(new java.awt.Color(247, 247, 247));
        backButton.setBorderPainted(false);
        backButton.setForeground(new java.awt.Color(0, 102, 204));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 584, -1, -1));
        add(datePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nurse_ser.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 540, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void EDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EDTextActionPerformed

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        // TODO add your handling code here:
         LocalDate dt = LocalDate.from(ZonedDateTime.now());
       if (datePicker1.getDate() == null || dt.compareTo(datePicker1.getDate()) > 0 )
         {
             JOptionPane.showMessageDialog(null,"Please pick valid date", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
         }
        
         if(EDText.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null,"Please enter the number of days of service", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }
         
            int days = Integer.parseInt(EDText.getText());
        Person person = ecoSystem.getPersonDirectory().getPerson(account.getEmployee().getName());
        //String customer = ((DriverWorkRequest) dreq).getPerson().getName();
        //Person address = ecoSystem.getPersonDirectory().getPerson(account.getEmployee().getAddress());
        LocalDate date = datePicker1.getDate();
       // LocalTime time = dateTimePicker1.getTimePicker().getTime();
        String status = "Nurse Requested";
        NurseWorkRequest nreq = new NurseWorkRequest();
        nreq.setDays(days);
        nreq.setPerson(person);
        nreq.setDate(date);
        nreq.setNstatus(status);
        
         account.getWorkQueue().getWorkRequestList().add(nreq);
        ecoSystem.getWorkQueue().getWorkRequestList().add(nreq);
        
         JOptionPane.showMessageDialog(null,"You have successfully requested a nurse. Please wait for the nurse to accept");
        populateRequestTable();
         
    }//GEN-LAST:event_bookButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PersonAreaJPanel a = (PersonAreaJPanel) component;
        //a.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EDText;
    private javax.swing.JButton backButton;
    private javax.swing.JButton bookButton;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel priceText;
    // End of variables declaration//GEN-END:variables
}
