/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PersonRole;

import Business.DeliveryMan.DeliveryManDirectory;
import Business.Doctor.DoctorDirectory;
import Business.Driver.DriverDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Grocer.GrocerDirectory;
import Business.Helper.HelperDirectory;
import Business.Network.Network;
import Business.Nurse.NurseDirectory;
import Business.Org.Org;
import Business.Org.PersonOrganization;
import Business.Person.PersonDirectory;
import Business.Pharmacy.PharmacyDirectory;
import Business.PharmacyMenu.PMenuDirectory;
import Business.PharmacyOrder.POrderDirectory;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.DoctorWorkRequest;
import Business.WorkQueue.DriverWorkRequest;
import Business.WorkQueue.HelperWorkRequest;
import Business.WorkQueue.NurseWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.SystemAdminWorkArea.ManageDeliveryServicesJPanel;

/**
 *
 * @author grees
 */
public class PersonAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;

    private UserAccount userAccount;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    EcoSystem ecosystem;
    GrocerDirectory grocerDirectory;
    PharmacyDirectory pharmacyDirectory;
    DoctorDirectory doctorDirectory;
    HelperDirectory helperDirectory;
    NurseDirectory nurseDirectory;
    PersonDirectory personDirectory;
    DriverDirectory driverDirectory;
    DriverWorkRequest dreq;
    NurseWorkRequest nreq;
    HelperWorkRequest hreq;
    DoctorWorkRequest docreq;
    Enterprise enterprise;
    Network network;
    Org organization;
    //JPanel userProcessContainer, UserAccount account, EcoSystem ecoSystem,HelperWorkRequest hreq,Enterprise ent,Network network,PersonOrganization organization
    public PersonAreaJPanel(JPanel userProcessContainer, UserAccount account, Org organization, Enterprise enterprise, EcoSystem ecoSystem,Network network) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
      
        this.userAccount = account;
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecoSystem;
        this.enterprise = enterprise;
        this.network = network; 
        this.organization = organization;
       // populateRequestTable();
    }
    
 

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NursingButton = new javax.swing.JButton();
        helperButton = new javax.swing.JButton();
        cabButton = new javax.swing.JButton();
        HealthButton = new javax.swing.JButton();
        mediButton = new javax.swing.JButton();
        GrocerButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NursingButton.setBackground(new java.awt.Color(255, 255, 255));
        NursingButton.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        NursingButton.setForeground(new java.awt.Color(0, 102, 204));
        NursingButton.setText("Book a Nurse");
        NursingButton.setBorderPainted(false);
        NursingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NursingButtonActionPerformed(evt);
            }
        });
        add(NursingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 310, 80));

        helperButton.setBackground(new java.awt.Color(255, 255, 255));
        helperButton.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        helperButton.setForeground(new java.awt.Color(0, 102, 204));
        helperButton.setText("Book a Handy Man");
        helperButton.setBorderPainted(false);
        helperButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helperButtonActionPerformed(evt);
            }
        });
        add(helperButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 310, 80));

        cabButton.setBackground(new java.awt.Color(255, 255, 255));
        cabButton.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        cabButton.setForeground(new java.awt.Color(0, 102, 204));
        cabButton.setText("Book a Cab");
        cabButton.setBorderPainted(false);
        cabButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cabButtonActionPerformed(evt);
            }
        });
        add(cabButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 310, 80));

        HealthButton.setBackground(new java.awt.Color(255, 255, 255));
        HealthButton.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        HealthButton.setForeground(new java.awt.Color(0, 102, 204));
        HealthButton.setText("Book a Doctor Appointment");
        HealthButton.setBorderPainted(false);
        HealthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HealthButtonActionPerformed(evt);
            }
        });
        add(HealthButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 310, 80));

        mediButton.setBackground(new java.awt.Color(255, 255, 255));
        mediButton.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        mediButton.setForeground(new java.awt.Color(0, 102, 204));
        mediButton.setText("Buy Medicines");
        mediButton.setBorderPainted(false);
        mediButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediButtonActionPerformed(evt);
            }
        });
        add(mediButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 310, 80));

        GrocerButton.setBackground(new java.awt.Color(255, 255, 255));
        GrocerButton.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        GrocerButton.setForeground(new java.awt.Color(0, 102, 204));
        GrocerButton.setText("Buy Groceries");
        GrocerButton.setBorderPainted(false);
        GrocerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrocerButtonActionPerformed(evt);
            }
        });
        add(GrocerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 620, 310, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eldery-care.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 840, 240));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1750, 990));
    }// </editor-fold>//GEN-END:initComponents

    private void NursingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NursingButtonActionPerformed
        // TODO add your handling code here:
        
         NursingJPanel n = new NursingJPanel(userProcessContainer,userAccount, ecosystem,nreq,enterprise,network,(PersonOrganization) organization);
        userProcessContainer.add("NursingJPanel",n);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_NursingButtonActionPerformed

    private void cabButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cabButtonActionPerformed
        // TODO add your handling code here:
        
        CabJPanel n = new CabJPanel(userProcessContainer,userAccount, ecosystem,dreq,enterprise,network,(PersonOrganization) organization);
        userProcessContainer.add("CabJPanel",n);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_cabButtonActionPerformed

    private void helperButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helperButtonActionPerformed
        // TODO add your handling code here:
        
        HandyManJPanel n = new HandyManJPanel(userProcessContainer,userAccount, ecosystem,hreq,enterprise,network,(PersonOrganization) organization);
        userProcessContainer.add("HandyManJPanel",n);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_helperButtonActionPerformed

    private void mediButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediButtonActionPerformed
        // TODO add your handling code here:
        
         PharmacyJPanel n = new PharmacyJPanel(userProcessContainer, userAccount, ecosystem, 
            ecosystem.getPersonDirectory(), ecosystem.getPharmacyDirectory(), 
            ecosystem.getDeliverymanDirectory() , ecosystem.getpMenuDirectory() , ecosystem.getpOrderDirectory() );
        userProcessContainer.add("PharmacyJPanel",n);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_mediButtonActionPerformed

    private void GrocerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrocerButtonActionPerformed
        // TODO add your handling code here:
        
        GroceryJPanel n = new GroceryJPanel(userProcessContainer, userAccount, ecosystem, 
            ecosystem.getPersonDirectory(), ecosystem.getGrocerDirectory(), 
            ecosystem.getDeliverymanDirectory() , ecosystem.getgMenuDirectory() , ecosystem.getgOrderDirectory() );
        userProcessContainer.add("GroceryJPanel",n);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_GrocerButtonActionPerformed

    private void HealthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HealthButtonActionPerformed
        // TODO add your handling code here:
        DocJPanel docPanel = new DocJPanel(userProcessContainer,userAccount, ecosystem,docreq,enterprise,network,(PersonOrganization) organization);
userProcessContainer.add("DocJPanel",docPanel);
CardLayout layout=(CardLayout)userProcessContainer.getLayout();
layout.next(userProcessContainer);
        
    }//GEN-LAST:event_HealthButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GrocerButton;
    private javax.swing.JButton HealthButton;
    private javax.swing.JButton NursingButton;
    private javax.swing.JButton cabButton;
    private javax.swing.JButton helperButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton mediButton;
    // End of variables declaration//GEN-END:variables
}
