/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Role.DeliveryManRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author grees
 */
public class addDeliveryMan extends javax.swing.JPanel {

    /**
     * Creates new form addDeliveryMan
     */ private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private DeliveryManDirectory deliveryManDirectory;
    public addDeliveryMan(JPanel userProcessContainer, EcoSystem ecoSystem, DeliveryManDirectory deliveryManDirectory) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.deliveryManDirectory = ecoSystem.getDeliverymanDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLab1 = new javax.swing.JLabel();
        nameLable = new javax.swing.JLabel();
        mobileLable = new javax.swing.JLabel();
        emailLable = new javax.swing.JLabel();
        addLable1 = new javax.swing.JLabel();
        unLable = new javax.swing.JLabel();
        pwdLable = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        mobileText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        addText = new javax.swing.JTextField();
        unText = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setForeground(new java.awt.Color(0, 102, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleLab1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        TitleLab1.setForeground(new java.awt.Color(0, 102, 204));
        TitleLab1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLab1.setText("Add Delivery Man");
        add(TitleLab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 66, 389, -1));

        nameLable.setText("Name:");
        add(nameLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 155, 54, -1));

        mobileLable.setText("Mobile:");
        add(mobileLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 193, 54, -1));

        emailLable.setText("Email:");
        add(emailLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 228, 54, -1));

        addLable1.setText("Address:");
        add(addLable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 263, 54, -1));

        unLable.setText("User Name:");
        add(unLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 298, 73, -1));

        pwdLable.setText("Password:");
        add(pwdLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 333, 73, -1));

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 152, 168, -1));

        mobileText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileTextActionPerformed(evt);
            }
        });
        add(mobileText, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 190, 168, -1));

        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });
        add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 222, 168, -1));

        addText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTextActionPerformed(evt);
            }
        });
        add(addText, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 260, 168, -1));

        unText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unTextActionPerformed(evt);
            }
        });
        add(unText, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 292, 168, -1));

        BackButton.setBackground(new java.awt.Color(255, 255, 255));
        BackButton.setForeground(new java.awt.Color(0, 102, 204));
        BackButton.setText("<<Back");
        BackButton.setBorderPainted(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 438, -1, -1));

        addButton.setBackground(new java.awt.Color(0, 102, 204));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add Details");
        addButton.setBorderPainted(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 395, 185, -1));

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 330, 174, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1680, 920));
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void mobileTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileTextActionPerformed

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextActionPerformed

    private void addTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTextActionPerformed

    private void unTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unTextActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        manageDeliveryMan mcjp = (manageDeliveryMan) component;
        mcjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String mobile = mobileText.getText();
        String email = emailText.getText();
        String userName = unText.getText();
        String password = passwordField.getText();

        for(DeliveryMan deliveryMan : deliveryManDirectory.getDeliveryManDirectory()) {

            if(deliveryMan.getPhoneNumber().equals(mobile)) {
                JOptionPane.showMessageDialog(null, "Mobile Number already exists");
            }
        }
        for(DeliveryMan deliveryMan : deliveryManDirectory.getDeliveryManDirectory()) {

            if(deliveryMan.getEmail().equals(email)) {
                JOptionPane.showMessageDialog(null, "Email already exists");
            }
        }

        for(UserAccount account : ecoSystem.getUserAccountDirectory().getUserAccountList()) {
            if(account.getUsername().equals(userName)) {
                JOptionPane.showMessageDialog(null, "Username Already exists");
                return;
            }
        }

        if (nameText.getText().isEmpty() || !nameText.getText().matches("^[a-zA-Z]+(?:[\\s-][a-zA-Z]+)*$"))
        JOptionPane.showMessageDialog(null, "Please enter valid name");

        else if(!(mobileText.getText().length()==10) || !mobileText.getText().matches("^[0-9]+") || mobileText.getText().matches("[0]{10}"))
        JOptionPane.showMessageDialog(null, "enter valid mobile number");

        else if(emailText.getText().isEmpty()|| !(emailText.getText().trim().contains("@") && emailText.getText().trim().contains(".")))
        JOptionPane.showMessageDialog(null, "Enter valid email address");

        else if (addText.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter address");
        }

        else if (userName.isEmpty() || !userName.matches("^[a-zA-Z0-9]*$"))
        JOptionPane.showMessageDialog(null, "Please enter userName");

        else if (password.isEmpty() || !password.matches("^[a-zA-Z0-9]*$"))
        JOptionPane.showMessageDialog(null, "Please enter password");

        else
        {
            JOptionPane.showMessageDialog(null, "Delivery man Profile Created");

            ecoSystem.getDeliverymanDirectory().addDeliveryMan(nameText.getText(), addText.getText(), email, mobile);
            //Employee employee = ecoSystem.getEmployeeDirectory().createEmployee(nameText.getText());
            //UserAccount userAccount = ecoSystem.getUserAccountDirectory().createUserAccount(userName, password, employee, new CustomerRole());
            Employee employee = ecoSystem.getEmployeeDirectory().createEmployee(email);
            ecoSystem.getUserAccountDirectory().createUserAccount(userName, password, employee, new DeliveryManRole());

        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel TitleLab1;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addLable1;
    private javax.swing.JTextField addText;
    private javax.swing.JLabel emailLable;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mobileLable;
    private javax.swing.JTextField mobileText;
    private javax.swing.JLabel nameLable;
    private javax.swing.JTextField nameText;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel pwdLable;
    private javax.swing.JLabel unLable;
    private javax.swing.JTextField unText;
    // End of variables declaration//GEN-END:variables
}
