/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Driver.Driver;
import Business.EcoSystem;
import Business.Driver.DriverDirectory;
import Business.Employee.Employee;
import Business.Helper.Helper;
import Business.Helper.HelperDirectory;
import Business.Role.DriverRole;
import Business.Role.HelperRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author grees
 */
public class addDriver extends javax.swing.JPanel {

    /**
     * Creates new form addDriver
     */
     private JPanel userProcessContainer; 
    private EcoSystem ecosystem; 
    private DriverDirectory driverDirectory;
    public addDriver(JPanel userProcessContainer,EcoSystem ecosystem,DriverDirectory driverDirectory) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.driverDirectory = ecosystem.getDriverDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        carLabel = new javax.swing.JLabel();
        modelText = new javax.swing.JTextField();
        seatsLabel = new javax.swing.JLabel();
        seatsText = new javax.swing.JTextField();
        mobileLabel = new javax.swing.JLabel();
        mobileText = new javax.swing.JTextField();
        addLabel = new javax.swing.JLabel();
        addText = new javax.swing.JTextField();
        UILabel = new javax.swing.JLabel();
        UIText = new javax.swing.JTextField();
        pwdLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        NameLabel1 = new javax.swing.JLabel();
        nameText1 = new javax.swing.JTextField();
        emailLabel1 = new javax.swing.JLabel();
        emailText1 = new javax.swing.JTextField();
        pwdText = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Add Driver Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 380, 50));

        carLabel.setText("Car Model:");
        add(carLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 80, -1));
        add(modelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 180, -1));

        seatsLabel.setText("No. of seats:");
        add(seatsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 80, -1));
        add(seatsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 180, -1));

        mobileLabel.setText("Mobile:");
        add(mobileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 80, -1));
        add(mobileText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 180, -1));

        addLabel.setText("Address:");
        add(addLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 80, -1));

        addText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTextActionPerformed(evt);
            }
        });
        add(addText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 180, -1));

        UILabel.setText("User Name:");
        add(UILabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 80, -1));
        add(UIText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 180, -1));

        pwdLabel.setText("Password:");
        add(pwdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 80, -1));

        addButton.setBackground(new java.awt.Color(0, 102, 204));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add Details");
        addButton.setBorderPainted(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, -1, -1));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setForeground(new java.awt.Color(0, 102, 204));
        backButton.setText("<< BACK");
        backButton.setBorderPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, -1, -1));

        NameLabel1.setText("Name:");
        add(NameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 80, -1));
        add(nameText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 180, -1));

        emailLabel1.setText("Email:");
        add(emailLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 80, -1));
        add(emailText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 180, -1));
        add(pwdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 180, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1680, 880));
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
          String mobile = mobileText.getText();
        String email = emailText1.getText();
        String model = modelText.getText();
        String seats = seatsText.getText();
        String userName = UIText.getText();
        String password = pwdText.getText();
        
        
         for(Driver driver : driverDirectory.getDriverDirectory()) {
           
            if(driver.getMobile().equals(mobile)) {
                JOptionPane.showMessageDialog(null, "Mobile Number already exists");
            }
        }
         for(Driver driver : driverDirectory.getDriverDirectory()) {
           
            if(driver.getEmail().equals(email)) {
                JOptionPane.showMessageDialog(null, "Email already exists");
            }
        }
         
            for(UserAccount account : ecosystem.getUserAccountDirectory().getUserAccountList()) {
            if(account.getUsername().equals(userName)) {
                JOptionPane.showMessageDialog(null, "Username Already exists");
                return;
            }
        }
        
        if (nameText1.getText().isEmpty() || !nameText1.getText().matches("^[a-zA-Z]+(?:[\\s-][a-zA-Z]+)*$"))
          JOptionPane.showMessageDialog(null, "Please enter valid name");
        
        
        else if(!(mobileText.getText().length()==10) || !mobileText.getText().matches("^[0-9]+") || mobileText.getText().matches("[0]{10}"))
        JOptionPane.showMessageDialog(null, "enter valid mobile number");
        
      
       
        else if(emailText1.getText().isEmpty()|| !(emailText1.getText().trim().contains("@") && emailText1.getText().trim().contains(".")))
          JOptionPane.showMessageDialog(null, "Enter valid email address");
       
       
        else if (addText.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Please enter address");
        }
        
        else if (modelText.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Please enter model");
        }
        else if (seatsText.getText().isEmpty() || !seatsText.getText().matches("^[0-9]+"))
          JOptionPane.showMessageDialog(null, "Please enter valid seats");
        
        else if (userName.isEmpty() || !userName.matches("^[a-zA-Z0-9]*$"))
          JOptionPane.showMessageDialog(null, "Please enter userName");
        
        else if (password.isEmpty() || !password.matches("^[a-zA-Z0-9]*$"))
          JOptionPane.showMessageDialog(null, "Please enter password");
        
     
        else
           {
                   JOptionPane.showMessageDialog(null, "Driver Profile Created");
                   
        ecosystem.getDriverDirectory().addDriver(userName, nameText1.getText(), email, mobile, addText.getText(), modelText.getText(), Integer.parseInt(seatsText.getText()));
        Employee employee = ecosystem.getEmployeeDirectory().createEmployee(nameText1.getText());
        UserAccount userAccount = ecosystem.getUserAccountDirectory().createUserAccount(userName, password, employee, new DriverRole());
           }
    }//GEN-LAST:event_addButtonActionPerformed

    private void addTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTextActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    userProcessContainer.remove(this);
    Component[] componentArray = userProcessContainer.getComponents();
    Component component = componentArray[componentArray.length - 1];
    manageDriver driver = (manageDriver) component;
    driver.populateTable();
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameLabel1;
    private javax.swing.JLabel UILabel;
    private javax.swing.JTextField UIText;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addLabel;
    private javax.swing.JTextField addText;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel carLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JTextField emailText1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JTextField mobileText;
    private javax.swing.JTextField modelText;
    private javax.swing.JTextField nameText1;
    private javax.swing.JLabel pwdLabel;
    private javax.swing.JPasswordField pwdText;
    private javax.swing.JLabel seatsLabel;
    private javax.swing.JTextField seatsText;
    // End of variables declaration//GEN-END:variables
}
