/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Pharmacy.Pharmacy;
import Business.Pharmacy.PharmacyDirectory;

//import Business.Role.AdminRole;
import Business.Role.PharmaRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author grees
 */
public class addPharmacy extends javax.swing.JPanel {
     private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private PharmacyDirectory pharmacyDirectory;

    /**
     * Creates new form addPharmacy
     */
    public addPharmacy(JPanel userProcessContainer, EcoSystem ecoSystem, PharmacyDirectory pharmacyDirectory) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.pharmacyDirectory = ecoSystem.getPharmacyDirectory();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        mobileLabel = new javax.swing.JLabel();
        mobileText = new javax.swing.JTextField();
        addLabel = new javax.swing.JLabel();
        addText = new javax.swing.JTextField();
        UILabel = new javax.swing.JLabel();
        UIText = new javax.swing.JTextField();
        pwdLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        NameLabel1 = new javax.swing.JLabel();
        pharmacistText = new javax.swing.JTextField();
        pwdText = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Add Pharmacy Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 34, 430, 50));

        NameLabel.setText("Pharmacy Name:");
        add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 90, -1));
        add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 180, -1));

        mobileLabel.setText("Mobile:");
        add(mobileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 80, -1));
        add(mobileText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 180, -1));

        addLabel.setText("Address:");
        add(addLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 80, -1));
        add(addText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 180, -1));

        UILabel.setText("UserID:");
        add(UILabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 80, -1));
        add(UIText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 180, -1));

        pwdLabel.setText("Password:");
        add(pwdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 80, -1));

        addButton.setBackground(new java.awt.Color(0, 102, 204));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add Details");
        addButton.setBorderPainted(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, -1));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 102, 204));
        backButton.setText("<< BACK");
        backButton.setBorderPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        NameLabel1.setText("Pharmacist:");
        add(NameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 90, -1));
        add(pharmacistText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 180, -1));
        add(pwdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 180, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1680, 880));
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String PharmacyName = nameText.getText();
        String address = addText.getText();
        String phone = mobileText.getText();
        String pName = pharmacistText.getText();
        String userName = UIText.getText();
        String password = pwdText.getText();
        
         for(Pharmacy pharmacy : pharmacyDirectory.getPharmacyDirectory()) {
           
            if(pharmacy.getPharmName().equals(PharmacyName)) {
                JOptionPane.showMessageDialog(null, "This pharmacy already exists");
            }
        }
         for(Pharmacy pharmacy : pharmacyDirectory.getPharmacyDirectory()) {
           
            if(pharmacy.getPhone().equals(phone)) {
                JOptionPane.showMessageDialog(null, "Phone number already exists");
            }
        }
         
          for(UserAccount account : ecoSystem.getUserAccountDirectory().getUserAccountList()) {
            if(account.getUsername().equals(userName)) {
                JOptionPane.showMessageDialog(null, "Username Already exists");
                return;
            }
        }
        
        if (PharmacyName.isEmpty() || !PharmacyName.matches("^[a-zA-Z]+(?:[\\s-][a-zA-Z]+)*$"))
          JOptionPane.showMessageDialog(null, "Please enter valid name");
        
        
        else if(!(phone.length()==10) || !phone.matches("^[0-9]+") || phone.matches("[0]{10}"))
        JOptionPane.showMessageDialog(null, "enter valid mobile number");
        
      
       
        /*else if(emailText.getText().isEmpty()|| !(emailText.getText().trim().contains("@") && emailText.getText().trim().contains(".")))
          JOptionPane.showMessageDialog(null, "Enter valid email address");*/
       
       
        else if (address.isEmpty()){
          JOptionPane.showMessageDialog(null, "Please enter address");
        }
        
        else if (pName.isEmpty() || !pName.matches("^[a-zA-Z]+(?:[\\s-][a-zA-Z]+)*$"))
          JOptionPane.showMessageDialog(null, "Please enter valid name");
        
        else if (userName.isEmpty() || !userName.matches("^[a-zA-Z0-9]*$"))
          JOptionPane.showMessageDialog(null, "Please enter userName");
        
        else if (password.isEmpty() || !password.matches("^[a-zA-Z0-9]*$"))
          JOptionPane.showMessageDialog(null, "Please enter password");
        
     
        else
           {
                   JOptionPane.showMessageDialog(null, "Pharmacy Profile Created");
                   
        /*ecoSystem.getCustomerDirectory().addCustomer(userName, nameText.getText(), email, mobile, addText.getText());
        Employee employee = ecoSystem.getEmployeeDirectory().createEmployee(nameText.getText());
        UserAccount userAccount = ecoSystem.getUserAccountDirectory().createUserAccount(userName, password, employee, new CustomerRole());
        */
        
        ecoSystem.getPharmacyDirectory().addPharmacy(PharmacyName, address, phone, pName);
        Employee employee = ecoSystem.getEmployeeDirectory().createEmployee(PharmacyName);
        UserAccount userAccount = ecoSystem.getUserAccountDirectory().createUserAccount(userName, password, employee, new PharmaRole());
           }
    }//GEN-LAST:event_addButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
         Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        managePharmacy m = (managePharmacy) component;
        m.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel NameLabel1;
    private javax.swing.JLabel UILabel;
    private javax.swing.JTextField UIText;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addLabel;
    private javax.swing.JTextField addText;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JTextField mobileText;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField pharmacistText;
    private javax.swing.JLabel pwdLabel;
    private javax.swing.JPasswordField pwdText;
    // End of variables declaration//GEN-END:variables
}
