/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Grocer.Grocer;
import Business.Grocer.GrocerDirectory;
import Business.Role.DoctorRole;
import Business.Role.GrocerRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 16178
 */
public class CreateGrocer extends javax.swing.JPanel {

    /**
     * Creates new form CreateGrocer
     */
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private GrocerDirectory grocerDirectory;
    public CreateGrocer(JPanel userProcessContainer,EcoSystem ecosystem,GrocerDirectory grocerDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.grocerDirectory = ecosystem.getGrocerDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        managerText = new javax.swing.JTextField();
        mobileLabel = new javax.swing.JLabel();
        mobileText = new javax.swing.JTextField();
        UILabel = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();
        UIText = new javax.swing.JTextField();
        specialityLabel = new javax.swing.JLabel();
        pwdLabel = new javax.swing.JLabel();
        pwdText = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameLabel.setText("Grocer Name:");
        add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 182, 80, -1));
        add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 182, 180, -1));

        emailLabel.setText("Manager:");
        add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 80, -1));

        managerText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerTextActionPerformed(evt);
            }
        });
        add(managerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 281, 180, -1));

        mobileLabel.setText("Phone Number:");
        add(mobileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 325, 80, -1));
        add(mobileText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 322, 180, -1));

        UILabel.setText("UserID:");
        add(UILabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 377, 80, -1));

        addressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextActionPerformed(evt);
            }
        });
        add(addressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 233, 180, -1));

        UIText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UITextActionPerformed(evt);
            }
        });
        add(UIText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 374, 180, -1));

        specialityLabel.setText("Address:");
        add(specialityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 233, 80, -1));

        pwdLabel.setText("Password:");
        add(pwdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 428, 80, -1));

        pwdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdTextActionPerformed(evt);
            }
        });
        add(pwdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 428, 180, -1));

        addButton.setBackground(new java.awt.Color(0, 102, 204));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add Details");
        addButton.setBorderPainted(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, -1, -1));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 102, 204));
        btnBack.setText("<< Back");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 486, -1, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setText("Create Grocer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 54, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -130, 1800, 1190));
    }// </editor-fold>//GEN-END:initComponents

    private void managerTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managerTextActionPerformed

    private void addressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String mobile = mobileText.getText();
        String address = addressText.getText();
        String userName = UIText.getText();
        String password = pwdText.getText();
        String name = nameText.getText();
        
        
         for(Grocer grocer : grocerDirectory.getGrocerDirectory()) {
           
            if(grocer.getPhoneNum().equals(mobile)) {
                JOptionPane.showMessageDialog(null, "Mobile Number already exists"); //obile Number already exists
            }
        }
        
         
            for(UserAccount account : ecosystem.getUserAccountDirectory().getUserAccountList()) {
            if(account.getUsername().equals(userName)) {
                JOptionPane.showMessageDialog(null, "Username Already exists");//Username Already exists
                return;
            }
        }
        
        if (nameText.getText().isEmpty() || !nameText.getText().matches("^[a-zA-Z]+(?:[\\s-][a-zA-Z]+)*$"))
          JOptionPane.showMessageDialog(null, "Please enter valid name");//Please enter valid name
        
        
        else if(!(mobileText.getText().length()==10) || !mobileText.getText().matches("^[0-9]+") || mobileText.getText().matches("[0]{10}"))
        JOptionPane.showMessageDialog(null, "enter valid mobile number");//enter valid mobile number
                   
       
        else if (address.isEmpty()){
          JOptionPane.showMessageDialog(null, "Please enter address");//Please enter address
        }
        
        
        else if (userName.isEmpty() || !userName.matches("^[a-zA-Z0-9]*$"))
          JOptionPane.showMessageDialog(null, "Please enter userName");
        
        else if (password.isEmpty() || !password.matches("^[a-zA-Z0-9]*$"))
          JOptionPane.showMessageDialog(null, "Please enter password");
     
        else
           {
                   JOptionPane.showMessageDialog(null, "Grocer Profile Created");
                   
        ecosystem.getGrocerDirectory().newGrocer(name,address,managerText.getText(),mobile); 
        
        Employee employee = ecosystem.getEmployeeDirectory().createEmployee(nameText.getText());
        UserAccount userAccount = ecosystem.getUserAccountDirectory().createUserAccount(userName, password, employee, new GrocerRole());
           }
    }//GEN-LAST:event_addButtonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageGrocer grocer = (ManageGrocer) component;
        grocer.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void pwdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdTextActionPerformed

    private void UITextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UITextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UITextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel UILabel;
    private javax.swing.JTextField UIText;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField addressText;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField managerText;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JTextField mobileText;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel pwdLabel;
    private javax.swing.JTextField pwdText;
    private javax.swing.JLabel specialityLabel;
    // End of variables declaration//GEN-END:variables
}
