/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.Role.PersonRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author harshavardhani
 */
public class CreatePatient extends javax.swing.JPanel {

    /**
     * Creates new form CreatePatient
     */
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private PersonDirectory personDirectory;
    public CreatePatient(JPanel userProcessContainer,EcoSystem ecoSystem,PersonDirectory personDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.personDirectory = ecoSystem.getPersonDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        genderText = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        phonenumberText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ageText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        pwdText = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreate.setBackground(new java.awt.Color(0, 102, 204));
        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("CREATE");
        btnCreate.setBorderPainted(false);
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, 94, -1));
        jPanel1.add(genderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 198, 169, 32));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 102, 204));
        btnBack.setText("<<Back");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 553, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("NAME :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 97, 71, -1));

        addressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextActionPerformed(evt);
            }
        });
        jPanel1.add(addressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 248, 169, 34));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setText("PASSWORD :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 478, 110, 46));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("AGE :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 148, -1, -1));
        jPanel1.add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 300, 169, 34));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("GENDER :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));
        jPanel1.add(phonenumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 355, 169, 34));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("ADDRESS :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 254, -1, -1));
        jPanel1.add(usernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 414, 169, 34));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("E-MAIL :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 309, -1, -1));

        ageText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextActionPerformed(evt);
            }
        });
        jPanel1.add(ageText, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 146, 169, 34));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setText("PHONE NUMBER :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 352, -1, 34));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("USERNAME :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 416, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel2.setText("CREATE PATIENT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 18, 385, -1));
        jPanel1.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 87, 169, 34));
        jPanel1.add(pwdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 478, 169, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d1.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1680, 970));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if(nameText.getText().isEmpty() ||
        ageText.getText().isEmpty() || genderText.getText().isEmpty() || addressText.getText().isEmpty() ||
        addressText.getText().isEmpty() || emailText.getText().isEmpty() || phonenumberText.getText().isEmpty()
        || usernameText.getText().isEmpty() || pwdText.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Fields cannot be left empty");//Fields cannot be left empty
        return;
        }

        String Name = nameText.getText();


        boolean flag ;

        flag = Name.matches("^[a-zA-Z]+$");

        if(flag == false) {
        JOptionPane.showMessageDialog(null, "name cannot have integer values"); //name cannot have integer values
        return;
        }

        String name = Name;

        String email = emailText.getText();

        flag = email.matches("^[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]+$");

        if(!flag) {
        JOptionPane.showMessageDialog(null, "Email Address must be in format of X@Y.Z");//Email Address must be in format of X@Y.Z
        return;
        }

        for(Person person : ecoSystem.getPersonDirectory().getPersonDirectory()) {
        if(person.getEmail().equals(email)) {
        JOptionPane.showMessageDialog(null, "Email Address already exists");//Email Address already exist
        }
        }

        String phoneNumber = phonenumberText.getText();

        if(phoneNumber.length() != 10) {
        JOptionPane.showMessageDialog(null, "PhoneNumber must be of 10 digits");//PhoneNumber must be of 10 digits
        return;
        }
        flag = phoneNumber.matches("^[0-9]+$");
        if(!flag) {
        JOptionPane.showMessageDialog(null, "Phone Number must have digits only");//Phone Number must have digits only
        return;
        }
        for(Person person : personDirectory.getPersonDirectory()) {
        if(person.getMobile().equals(phoneNumber)) {
        JOptionPane.showMessageDialog(null, "Phone Number already exists");//Phone Number already exists
        }
        }

        int age = 0;

        try {

        age = Integer.parseInt(ageText.getText());

        } catch(Exception e) {
        JOptionPane.showMessageDialog(null, "Age must have integers only");
        return;
        }

        String address = addressText.getText();
        String userName = usernameText.getText();
        String password = pwdText.getText();
        //String dob = dobText.getText();
        String phonenumber = phonenumberText.getText();
        String gender = genderText.getText();



        for(UserAccount account : ecoSystem.getUserAccountDirectory().getUserAccountList()) {
        if(account.getUsername().equals(userName)) {
        JOptionPane.showMessageDialog(null, "Username Already exists");
        return;
        }
        }

        System.out.println(ecoSystem.toString());
        ecoSystem.getPersonDirectory().addPerson(userName, gender, name, email, phonenumber, address, ageText.getText());
        Employee employee = ecoSystem.getEmployeeDirectory().createEmployee(name);
        UserAccount usserAccount = ecoSystem.getUserAccountDirectory().createUserAccount(userName, password, employee, new PersonRole());

        JOptionPane.showMessageDialog(null, "Customer Profile Created");
        

       

        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManagePatient mcjp = (ManagePatient) component;
        mcjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void addressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextActionPerformed

    private void ageTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressText;
    private javax.swing.JTextField ageText;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JTextField emailText;
    private javax.swing.JTextField genderText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField phonenumberText;
    private javax.swing.JPasswordField pwdText;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
