/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Doctor.Doctor;
import Business.Doctor.DoctorDirectory;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Role.DoctorRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author harshavardhani
 */
public class CreateDoctor extends javax.swing.JPanel {

    /**
     * Creates new form CreateDoctor
     */
    private JPanel userProcessContainer; 
    private EcoSystem ecosystem; 
    private DoctorDirectory doctorDirectory;
    public CreateDoctor(JPanel userProcessContainer,EcoSystem ecosystem,DoctorDirectory doctorDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.doctorDirectory = doctorDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        mobileLabel = new javax.swing.JLabel();
        mobileText = new javax.swing.JTextField();
        addLabel = new javax.swing.JLabel();
        addText = new javax.swing.JTextField();
        UILabel = new javax.swing.JLabel();
        UIText = new javax.swing.JTextField();
        pwdLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        specialityText = new javax.swing.JTextField();
        specialityLabel = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        pwdText = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Create Doctor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        NameLabel.setText("Name:");
        add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 80, -1));
        add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 180, -1));

        emailLabel.setText("Email:");
        add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 80, -1));

        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });
        add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 180, -1));

        mobileLabel.setText("Mobile:");
        add(mobileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 80, -1));
        add(mobileText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 180, -1));

        addLabel.setText("Address:");
        add(addLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 80, -1));

        addText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTextActionPerformed(evt);
            }
        });
        add(addText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 180, -1));

        UILabel.setText("UserID:");
        add(UILabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 80, -1));
        add(UIText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 180, -1));

        pwdLabel.setText("Password:");
        add(pwdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 80, -1));

        addButton.setBackground(new java.awt.Color(0, 102, 204));
        addButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add Details");
        addButton.setBorderPainted(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, -1));

        specialityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialityTextActionPerformed(evt);
            }
        });
        add(specialityText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 180, -1));

        specialityLabel.setText("Speciality:");
        add(specialityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 80, -1));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 102, 255));
        btnBack.setText("<< BACK");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, -1, -1));

        pwdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdTextActionPerformed(evt);
            }
        });
        add(pwdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 429, 180, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -650, 1680, 2230));
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
          String mobile = mobileText.getText();
        String email = emailText.getText();
        String userName = UIText.getText();
        String password = pwdText.getText();
        
        
         for(Doctor doctor : doctorDirectory.getDoctorDirectory()) {
           
            if(doctor.getMobile().equals(mobile)) {
                JOptionPane.showMessageDialog(null, "Mobile Number already exists"); //Mobile Number already exists
            }
        }
         for(Doctor doctor : doctorDirectory.getDoctorDirectory()) {
           
            if(doctor.getEmail().equals(email)) {
                JOptionPane.showMessageDialog(null, "Email already exists");//Email already exists
        }
         }
            for(UserAccount account : ecosystem.getUserAccountDirectory().getUserAccountList()) {
            if(account.getUsername().equals(userName)) {
                JOptionPane.showMessageDialog(null, "Username Already exists");//Username Already exists
                return;
            }
        }
        
        if (nameText.getText().isEmpty() || !nameText.getText().matches("^[a-zA-Z]+(?:[\\s-][a-zA-Z]+)*$"))
          JOptionPane.showMessageDialog(null, "Please enter valid name");//Please enter valid name
        
        
        else if(!(mobileText.getText().length()==10) || !mobileText.getText().matches("^[0-9]+") || mobileText.getText().matches("[0]{10}"))
        JOptionPane.showMessageDialog(null, "enter valid mobile number");//enter valid mobile number
        
      
       
        else if(emailText.getText().isEmpty()|| !(emailText.getText().trim().contains("@") && emailText.getText().trim().contains(".")))
          JOptionPane.showMessageDialog(null, "Enter valid email address");//Enter valid email address
       
       
        else if (addText.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Please enter address");//Please enter address
        }
        
        else if (addText.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Please enter model");//Please enter model
        }
        
        else if (userName.isEmpty() || !userName.matches("^[a-zA-Z0-9]*$"))
          JOptionPane.showMessageDialog(null, "Please enter userName");//Please enter userName
        
        else if (password.isEmpty() || !password.matches("^[a-zA-Z0-9]*$"))
          JOptionPane.showMessageDialog(null, "Please enter password");//Please enter password
        
     
        else
           {
                   JOptionPane.showMessageDialog(null, "Doctor Profile Created");//Doctor Profile Created
                   
        ecosystem.getDoctorDirectory().newDoctor(userName,nameText.getText(),addText.getText(), email, mobile,specialityText.getText());
        Employee employee = ecosystem.getEmployeeDirectory().createEmployee(nameText.getText());
        UserAccount userAccount = ecosystem.getUserAccountDirectory().createUserAccount(userName, password, employee, new DoctorRole());
           }
         

    }//GEN-LAST:event_addButtonActionPerformed

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextActionPerformed

    private void specialityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialityTextActionPerformed

    private void addTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageDoctor mngDoc = (ManageDoctor) component;
        mngDoc.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void pwdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel UILabel;
    private javax.swing.JTextField UIText;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addLabel;
    private javax.swing.JTextField addText;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JTextField mobileText;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel pwdLabel;
    private javax.swing.JPasswordField pwdText;
    private javax.swing.JLabel specialityLabel;
    private javax.swing.JTextField specialityText;
    // End of variables declaration//GEN-END:variables
}
