/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SystemAdminWorkArea;

import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Grocer.GrocerDirectory;
import Business.Pharmacy.PharmacyDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author harshavardhani
 */
public class ManageDeliveryServicesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryServicesJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    GrocerDirectory grocerDirectory;
    PharmacyDirectory pharmacyDirectory;
    DeliveryManDirectory deliveryManDirectory;
    public ManageDeliveryServicesJPanel(JPanel userProcessContainer,EcoSystem ecosystem,GrocerDirectory grocerDirectory,PharmacyDirectory pharmacyDirectory,DeliveryManDirectory deliveryManDirectory) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        this.grocerDirectory =grocerDirectory;
        this.pharmacyDirectory = pharmacyDirectory;
        this.deliveryManDirectory = deliveryManDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnManageGrocer = new javax.swing.JButton();
        btnManagePharamcy = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnManageDeliveryman = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(1710, 1047));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Manage Delivery Services");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, 39));

        btnManageGrocer.setBackground(new java.awt.Color(255, 255, 255));
        btnManageGrocer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnManageGrocer.setForeground(new java.awt.Color(0, 102, 204));
        btnManageGrocer.setText("Manage Grocer");
        btnManageGrocer.setBorderPainted(false);
        btnManageGrocer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageGrocerActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageGrocer, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 181, 214, 53));

        btnManagePharamcy.setBackground(new java.awt.Color(255, 255, 255));
        btnManagePharamcy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnManagePharamcy.setForeground(new java.awt.Color(0, 102, 204));
        btnManagePharamcy.setText("Manage Pharmacy");
        btnManagePharamcy.setBorderPainted(false);
        btnManagePharamcy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePharamcyActionPerformed(evt);
            }
        });
        jPanel1.add(btnManagePharamcy, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 266, 214, 55));

        btnBack.setBackground(new java.awt.Color(0, 102, 204));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 444, -1, -1));

        btnManageDeliveryman.setBackground(new java.awt.Color(255, 255, 255));
        btnManageDeliveryman.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnManageDeliveryman.setForeground(new java.awt.Color(0, 102, 204));
        btnManageDeliveryman.setText("Manage Deliveryman");
        btnManageDeliveryman.setBorderPainted(false);
        btnManageDeliveryman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDeliverymanActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageDeliveryman, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 214, 55));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manage-removebg-preview.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, -30, 500, 500));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d1.png"))); // NOI18N
        jLabel3.setText("jLabel2");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1710, 1000));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1680, 1047));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageGrocerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageGrocerActionPerformed
        // TODO add your handling code here:
        ManageGrocer mngGrocerPanel = new ManageGrocer(userProcessContainer,ecosystem,grocerDirectory);
       userProcessContainer.add("ManageDeliveryMan", mngGrocerPanel);
       CardLayout layout=(CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageGrocerActionPerformed

    private void btnManagePharamcyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePharamcyActionPerformed
        // TODO add your handling code here:
        managePharmacy mngPharmPanel = new managePharmacy(userProcessContainer,ecosystem,pharmacyDirectory);
       userProcessContainer.add("ManageDeliveryMan", mngPharmPanel);
       CardLayout layout=(CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManagePharamcyActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnManageDeliverymanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDeliverymanActionPerformed
        // TODO add your handling code here:
        manageDeliveryMan manageDeliveryMan = new manageDeliveryMan(userProcessContainer,ecosystem,deliveryManDirectory);
       userProcessContainer.add("ManageDeliveryMan", manageDeliveryMan);
       CardLayout layout=(CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageDeliverymanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnManageDeliveryman;
    private javax.swing.JButton btnManageGrocer;
    private javax.swing.JButton btnManagePharamcy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
