/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Grocer.Grocer;
import Business.Grocer.GrocerDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 16178
 */
public class ManageGrocer extends javax.swing.JPanel {

    /**
     * Creates new form ManageGrocer
     */
    private JPanel userProcessContainer; 
    private EcoSystem ecosystem;
    private GrocerDirectory grocerDirectory;
    public ManageGrocer(JPanel userProcessContainer, EcoSystem ecosystem,GrocerDirectory grocerDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.grocerDirectory = ecosystem.getGrocerDirectory();
        populateTable();
    }
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblGrocer.getModel();
        model.setRowCount(0);
        for(Grocer grocer : grocerDirectory.getGrocerDirectory()){
            Object [] row = new Object[5];
            row[0] = grocer;
            row[1] = grocer.getAddress();
            row[2] = grocer.getManagerName();
            row[3] = grocer.getPhoneNum();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGrocer = new javax.swing.JTable();
        btnCreateGrocer = new javax.swing.JButton();
        btnModifyGrocer = new javax.swing.JButton();
        btnDeleteGrocer = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Manage Grocer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        tblGrocer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grocer Name", "Address", "MangerName", "Phone Number"
            }
        ));
        jScrollPane1.setViewportView(tblGrocer);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 560, 170));

        btnCreateGrocer.setBackground(new java.awt.Color(0, 102, 204));
        btnCreateGrocer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCreateGrocer.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateGrocer.setText("Create Grocer");
        btnCreateGrocer.setBorderPainted(false);
        btnCreateGrocer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateGrocerActionPerformed(evt);
            }
        });
        add(btnCreateGrocer, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        btnModifyGrocer.setBackground(new java.awt.Color(0, 102, 204));
        btnModifyGrocer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModifyGrocer.setForeground(new java.awt.Color(255, 255, 255));
        btnModifyGrocer.setText("Update Grocer");
        btnModifyGrocer.setBorderPainted(false);
        btnModifyGrocer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyGrocerActionPerformed(evt);
            }
        });
        add(btnModifyGrocer, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));

        btnDeleteGrocer.setBackground(new java.awt.Color(0, 102, 204));
        btnDeleteGrocer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDeleteGrocer.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteGrocer.setText("Delete");
        btnDeleteGrocer.setBorderPainted(false);
        btnDeleteGrocer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteGrocerActionPerformed(evt);
            }
        });
        add(btnDeleteGrocer, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, -1, -1));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 102, 204));
        btnBack.setText("<<Back");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1680, 880));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateGrocerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateGrocerActionPerformed
        // TODO add your handling code here:
        CreateGrocer createGrocerPanel = new CreateGrocer(userProcessContainer, ecosystem, grocerDirectory);
        userProcessContainer.add("CreateGrocer",createGrocerPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnCreateGrocerActionPerformed

    private void btnDeleteGrocerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteGrocerActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblGrocer.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Grocer grocer = (Grocer) tblGrocer.getValueAt(selectedRow, 0);
        grocerDirectory.removeGrocer(grocer);
        populateTable();
    }//GEN-LAST:event_btnDeleteGrocerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnModifyGrocerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyGrocerActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblGrocer.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Grocer grocer = (Grocer) tblGrocer.getValueAt(selectedRow, 0);
        updateGrocer updateGrocerPanel = new updateGrocer(userProcessContainer, ecosystem, grocerDirectory,grocer);
        userProcessContainer.add("ManageGrocer",updateGrocerPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnModifyGrocerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateGrocer;
    private javax.swing.JButton btnDeleteGrocer;
    private javax.swing.JButton btnModifyGrocer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGrocer;
    // End of variables declaration//GEN-END:variables
}
