/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Helper.HelperDirectory;
import Business.Nurse.NurseDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author harshavardhani
 */
public class ManageSupportServicesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupportServicesJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    HelperDirectory helperDirectory;
    NurseDirectory nurseDirectory;
    public ManageSupportServicesJPanel(JPanel userProcessContainer,EcoSystem ecosystem,HelperDirectory helperDirectory,NurseDirectory nurseDirectory) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        this.helperDirectory = helperDirectory;
        this.nurseDirectory = nurseDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnManageHelper = new javax.swing.JButton();
        btnManageNurse = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Manage Support Services");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 104, 479, 43));

        btnManageHelper.setBackground(new java.awt.Color(255, 255, 255));
        btnManageHelper.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnManageHelper.setForeground(new java.awt.Color(0, 102, 204));
        btnManageHelper.setText("Manage Helper");
        btnManageHelper.setBorderPainted(false);
        btnManageHelper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageHelperActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageHelper, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 212, 244, 71));

        btnManageNurse.setBackground(new java.awt.Color(255, 255, 255));
        btnManageNurse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnManageNurse.setForeground(new java.awt.Color(0, 102, 204));
        btnManageNurse.setText("Manage Nursing  ");
        btnManageNurse.setBorderPainted(false);
        btnManageNurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNurseActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageNurse, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 350, 244, 75));

        btnBack.setBackground(new java.awt.Color(0, 102, 204));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 492, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manage-removebg-preview.png"))); // NOI18N
        jLabel5.setText("jLabel3");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 510, 480));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d1.png"))); // NOI18N
        jLabel7.setText("jLabel2");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1710, 1000));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1680, 1050));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageHelperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageHelperActionPerformed
        // TODO add your handling code here:
        manageHelper manageHelperPanel = new manageHelper(userProcessContainer,ecosystem,helperDirectory);
       userProcessContainer.add("manageHelper", manageHelperPanel);
       CardLayout layout=(CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageHelperActionPerformed

    private void btnManageNurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNurseActionPerformed
        // TODO add your handling code here:
        ManageNurse manageNursePanel = new ManageNurse(userProcessContainer,ecosystem,nurseDirectory);
       userProcessContainer.add("ManageNurse", manageNursePanel);
       CardLayout layout=(CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageNurseActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnManageHelper;
    private javax.swing.JButton btnManageNurse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
