/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author harshavardhani
 */
public class ModifyPatient extends javax.swing.JPanel {

    /**
     * Creates new form UpdatePatient
     */
     private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private PersonDirectory personDirectory;
    private Person person;
    public ModifyPatient(JPanel userProcessContainer,EcoSystem ecoSystem,PersonDirectory personDirectory,Person person) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.personDirectory = ecoSystem.getPersonDirectory();
        this.person = person;
        nameText.setText(person.getName());
        emailText.setText(person.getEmail());
        addressText.setText(person.getAddress());
        phonenumberText.setText(person.getMobile());
        //dobText.setText(person.getDob());
        ageText.setText(person.getAge());
        genderText.setText(person.getGender());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        genderText = new javax.swing.JTextField();
        addressText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        phonenumberText = new javax.swing.JTextField();
        ageText = new javax.swing.JTextField();
        btnModify = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("MODIFY PATIENT");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 19, 385, -1));
        jPanel2.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 87, 169, 34));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("NAME :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 97, 71, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("AGE :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 152, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("GENDER :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 212, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("ADDRESS :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 263, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("E-MAIL :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 315, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 204));
        jLabel8.setText("PHONE NUMBER :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 365, -1, 34));
        jPanel2.add(genderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 211, 169, 32));

        addressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextActionPerformed(evt);
            }
        });
        jPanel2.add(addressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 261, 169, 34));
        jPanel2.add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 313, 169, 34));
        jPanel2.add(phonenumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 368, 169, 34));
        jPanel2.add(ageText, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 150, 169, 34));

        btnModify.setBackground(new java.awt.Color(0, 102, 204));
        btnModify.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModify.setForeground(new java.awt.Color(255, 255, 255));
        btnModify.setText("Modify");
        btnModify.setBorderPainted(false);
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        jPanel2.add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 445, 94, -1));

        btnBack.setBackground(new java.awt.Color(0, 102, 204));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<Back");
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 445, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1680, 870));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1680, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void addressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
        if(nameText.getText().isEmpty() ||
        ageText.getText().isEmpty() || genderText.getText().isEmpty() || addressText.getText().isEmpty() ||
        addressText.getText().isEmpty() || emailText.getText().isEmpty() || phonenumberText.getText().isEmpty()
        ) {
        JOptionPane.showMessageDialog(null, "Fields cannot be left empty");
        return;
        }

        String Name = nameText.getText();


        boolean flag ;

        flag = Name.matches("^[a-zA-Z]+$");

        if(flag == false) {
        JOptionPane.showMessageDialog(null, "name cannot have integer values");
        return;
        }

        String name = Name;

        String email = emailText.getText();

        flag = email.matches("^[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]+$");

        if(!flag) {
        JOptionPane.showMessageDialog(null, "Email Address must be in format of X@Y.Z");
        return;
        }

        for(Person person : ecoSystem.getPersonDirectory().getPersonDirectory()) {
        if(person.getEmail().equals(email) && this.person != person) {
        JOptionPane.showMessageDialog(null, "Email Address already exists");
        }
        }

        String phoneNumber = phonenumberText.getText();

        if(phoneNumber.length() != 10) {
        JOptionPane.showMessageDialog(null, "PhoneNumber must be of 10 digits");
        return;
        }
        flag = phoneNumber.matches("^[0-9]+$");
        if(!flag) {
        JOptionPane.showMessageDialog(null, "Phone Number must have digits only");
        return;
        }
        for(Person person : personDirectory.getPersonDirectory()) {
        if(person.getMobile().equals(phoneNumber) && this.person != person) {
        JOptionPane.showMessageDialog(null, "Phone Number already exists");
        }
        }

        int age = 0;

        try {

        age = Integer.parseInt(ageText.getText());

        } catch(Exception e) {
        JOptionPane.showMessageDialog(null, "Age must have integers only");
        return;
        }
        person.setName(name);
        person.setAge( Integer.toString (age));
        person.setGender(genderText.getText());
        person.setAddress(addressText.getText()); 
        //person.setDob(dobText.getText());
        person.setMobile(phonenumberText.getText());
        person.setEmail(email);
       JOptionPane.showMessageDialog(null, "Person profile update");
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManagePatient mcjp = (ManagePatient) component;
        mcjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressText;
    private javax.swing.JTextField ageText;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnModify;
    private javax.swing.JTextField emailText;
    private javax.swing.JTextField genderText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField phonenumberText;
    // End of variables declaration//GEN-END:variables
}
