/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Doctor.Doctor;
import Business.Doctor.DoctorDirectory;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 16178
 */
public class updateDoctor extends javax.swing.JPanel {

    /**
     * Creates new form updateDoctor
     */
    private JPanel userProcessContainer; 
    private EcoSystem ecosystem; 
    private DoctorDirectory doctorDirectory;
    private Doctor doctor;
    public updateDoctor(JPanel userProcessContainer,EcoSystem ecosystem,DoctorDirectory doctorDirectory,Doctor doctor) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.doctorDirectory = doctorDirectory;
        this.doctor = doctor;
        mobileText.setText(doctor.getMobile());
        nameText.setText(doctor.getName());
        specialityText.setText(doctor.getSpeciality());
        emailText.setText(doctor.getEmail());
        addText.setText(doctor.getAddress());    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mobileText = new javax.swing.JTextField();
        addLabel = new javax.swing.JLabel();
        addText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        modifyButton = new javax.swing.JButton();
        emailLabel = new javax.swing.JLabel();
        specialityText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        specialityLabel = new javax.swing.JLabel();
        mobileLabel = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(mobileText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 325, 180, -1));

        addLabel.setText("Address:");
        add(addLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 376, 80, -1));

        addText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTextActionPerformed(evt);
            }
        });
        add(addText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 376, 180, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Modify Doctor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 54, -1, -1));

        NameLabel.setText("Name:");
        add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 182, 80, -1));
        add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 182, 180, -1));

        modifyButton.setText("Modify");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });
        add(modifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 448, -1, -1));

        emailLabel.setText("Email:");
        add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 284, 80, -1));

        specialityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialityTextActionPerformed(evt);
            }
        });
        add(specialityText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 233, 180, -1));

        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });
        add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 274, 180, -1));

        specialityLabel.setText("Speciality:");
        add(specialityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 233, 80, -1));

        mobileLabel.setText("Mobile:");
        add(mobileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 325, 80, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 448, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1710, 990));
    }// </editor-fold>//GEN-END:initComponents

    private void addTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTextActionPerformed

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        // TODO add your handling code here:
        String mobile = mobileText.getText();
        String email = emailText.getText();
        String speciality = specialityText.getText();
        String address = addText.getText();
        if(nameText.getText().isEmpty() || email.isEmpty() ||
        speciality.isEmpty() || address.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Fields cannot be left empty");
        return;
        }
        
        for(Doctor doctor : doctorDirectory.getDoctorDirectory()) {

            if(doctor.getMobile().equals(mobile) && this.doctor != doctor) {
                JOptionPane.showMessageDialog(null, "Mobile Number already exists");
            }
        }
        for(Doctor doctor : doctorDirectory.getDoctorDirectory()) {

            if(doctor.getEmail().equals(email) && this.doctor != doctor) {
                JOptionPane.showMessageDialog(null, "Email already exists");
            }
        }



        if (nameText.getText().isEmpty() || !nameText.getText().matches("^[a-zA-Z]+(?:[\\s-][a-zA-Z]+)*$"))
        JOptionPane.showMessageDialog(null, "Please enter valid name");

        else if(!(mobileText.getText().length()==10) || !mobileText.getText().matches("^[0-9]+") || mobileText.getText().matches("[0]{10}"))
        JOptionPane.showMessageDialog(null, "enter valid mobile number");

        else if(emailText.getText().isEmpty()|| !(emailText.getText().trim().contains("@") && emailText.getText().trim().contains(".")))
        JOptionPane.showMessageDialog(null, "Enter valid email address");

        else if (addText.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter address");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Doctor profile updated");

            doctor.setAddress(address);
            doctor.setEmail(email);
            doctor.setMobile(mobile);
            doctor.setName(nameText.getText());
            doctor.setSpeciality(speciality);
            
        }
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void specialityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialityTextActionPerformed

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageDoctor mngDoc = (ManageDoctor) component;
        mngDoc.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel addLabel;
    private javax.swing.JTextField addText;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JTextField mobileText;
    private javax.swing.JButton modifyButton;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel specialityLabel;
    private javax.swing.JTextField specialityText;
    // End of variables declaration//GEN-END:variables
}
