/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;



import Business.EcoSystem;
import Business.Helper.Helper;
import Business.Helper.HelperDirectory;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author grees
 */
public class updateHelper extends javax.swing.JPanel {

    /**
     * Creates new form updateHelper
     */
     private JPanel userProcessContainer;
     private EcoSystem ecoSystem;
    private Helper helper;
    private UserAccountDirectory userAccountDirectory;
    private HelperDirectory helperDirectory;
    public updateHelper(JPanel userProcessContainer, EcoSystem ecoSystem, HelperDirectory helperDirectory, Helper helper) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.helper = helper;
        this.helperDirectory = ecoSystem.getHelperDirectory();
        nameText.setText(helper.getName());
        emailText.setText(helper.getEmail());
        addText.setText(helper.getAddress());
        mobileText.setText(helper.getMobile());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        mobileLabel = new javax.swing.JLabel();
        mobileText = new javax.swing.JTextField();
        addLabel = new javax.swing.JLabel();
        addText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Update Helper Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 420, 50));

        updateButton.setBackground(new java.awt.Color(0, 102, 204));
        updateButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Update");
        updateButton.setBorderPainted(false);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 102, 204));
        backButton.setText("<< BACK");
        backButton.setBorderPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        NameLabel.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(0, 102, 204));
        NameLabel.setText("Name:");
        add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 80, -1));
        add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 180, -1));

        emailLabel.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(0, 102, 204));
        emailLabel.setText("Email:");
        add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 80, -1));
        add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 180, -1));

        mobileLabel.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        mobileLabel.setForeground(new java.awt.Color(0, 102, 204));
        mobileLabel.setText("Mobile:");
        add(mobileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 80, -1));
        add(mobileText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 180, -1));

        addLabel.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        addLabel.setForeground(new java.awt.Color(0, 102, 204));
        addLabel.setText("Address:");
        add(addLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 80, -1));

        addText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTextActionPerformed(evt);
            }
        });
        add(addText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 180, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1710, 990));
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
          String mobile = mobileText.getText();
        String email = emailText.getText();
  

        if (nameText.getText().isEmpty() || !nameText.getText().matches("^[a-zA-Z]+(?:[\\s-][a-zA-Z]+)*$"))
        JOptionPane.showMessageDialog(null, "Please enter valid name");

        if(!(mobileText.getText().length()==10) || !mobileText.getText().matches("^[0-9]+") || mobileText.getText().matches("[0]{10}"))
        JOptionPane.showMessageDialog(null, "enter valid mobile number");

        for(Helper helper : helperDirectory.getHelperDirectory()) {

            if(helper.getMobile().equals(mobile) && this.helper != helper) {
                JOptionPane.showMessageDialog(null, "Mobile Number already exists");
            }
        }

        if(emailText.getText().isEmpty()|| !(emailText.getText().trim().contains("@") && emailText.getText().trim().contains(".")))
        JOptionPane.showMessageDialog(null, "Enter valid email address");
        for(Helper helper : helperDirectory.getHelperDirectory()) {

            if(helper.getEmail().equals(email) && this.helper != helper) {
                JOptionPane.showMessageDialog(null, "Email already exists");
            }
        }

        if (addText.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Please enter address");

       
        helper.setMobile(mobileText.getText());
        helper.setAddress(addText.getText());
        helper.setName(nameText.getText());
        helper.setEmail(emailText.getText());
        
        
        JOptionPane.showMessageDialog(null, "Helper Profile Updated");
    }//GEN-LAST:event_updateButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        manageHelper helper = (manageHelper) component;
        helper.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void addTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel addLabel;
    private javax.swing.JTextField addText;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JTextField mobileText;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
