/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author grees
 */
public class updateDeliveryMan extends javax.swing.JPanel {

     private JPanel userProcessContainer; 
    private EcoSystem ecoSystem; 
    private DeliveryManDirectory deliveryManDirectory;
    private DeliveryMan deliveryMan;
    public updateDeliveryMan(JPanel userProcessContainer, EcoSystem ecoSystem, DeliveryManDirectory deliveryManDirectory, DeliveryMan deliveryMan) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.deliveryManDirectory = ecoSystem.getDeliverymanDirectory();
        this.ecoSystem = ecoSystem;
        this.deliveryMan = deliveryMan;
        nameText.setText(deliveryMan.getName());
        emailText.setText(deliveryMan.getEmail());
        addText.setText(deliveryMan.getAddress());
        mobileText.setText(deliveryMan.getPhoneNumber());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mobileLable = new javax.swing.JLabel();
        emailLable = new javax.swing.JLabel();
        addLable1 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        mobileText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        addText = new javax.swing.JTextField();
        TitleLab = new javax.swing.JLabel();
        nameLable = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mobileLable.setText("Mobile:");
        add(mobileLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 221, 54, -1));

        emailLable.setText("Email:");
        add(emailLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 256, 54, -1));

        addLable1.setText("Address:");
        add(addLable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 291, 54, -1));

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 180, 168, -1));

        mobileText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileTextActionPerformed(evt);
            }
        });
        add(mobileText, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 218, 168, -1));

        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });
        add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 250, 168, -1));

        addText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTextActionPerformed(evt);
            }
        });
        add(addText, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 288, 168, -1));

        TitleLab.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        TitleLab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLab.setText("Update Delivery Man");
        add(TitleLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 75, 450, -1));

        nameLable.setText("Name:");
        add(nameLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 183, 54, -1));

        updateButton.setText("Update Details");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 362, 185, -1));

        BackButton.setText("<<Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 362, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1710, 990));
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void mobileTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileTextActionPerformed

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextActionPerformed

    private void addTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTextActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        String mobile = mobileText.getText();
        String email = emailText.getText();

        if (nameText.getText().isEmpty() || !nameText.getText().matches("^[a-zA-Z]+(?:[\\s-][a-zA-Z]+)*$"))
        JOptionPane.showMessageDialog(null, "Please enter valid name");

        if(!(mobileText.getText().length()==10) || !mobileText.getText().matches("^[0-9]+") || mobileText.getText().matches("[0]{10}"))
        JOptionPane.showMessageDialog(null, "enter valid mobile number");

        for(DeliveryMan deliveryMan : deliveryManDirectory.getDeliveryManDirectory()) {

            if(deliveryMan.getPhoneNumber().equals(mobile) && this.deliveryMan != deliveryMan) {
                JOptionPane.showMessageDialog(null, "Mobile Number already exists");
            }
        }

        if(emailText.getText().isEmpty()|| !(emailText.getText().trim().contains("@") && emailText.getText().trim().contains(".")))
        JOptionPane.showMessageDialog(null, "Enter valid email address");
        for(DeliveryMan deliveryMan : deliveryManDirectory.getDeliveryManDirectory()) {

            if(deliveryMan.getEmail().equals(email) && this.deliveryMan != deliveryMan) {
                JOptionPane.showMessageDialog(null, "Email already exists");
            }
        }

        if (addText.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Please enter address");

        deliveryMan.setPhoneNumber(mobileText.getText());
        deliveryMan.setAddress(addText.getText());
        deliveryMan.setName(nameText.getText());
        deliveryMan.setEmail(emailText.getText());

        JOptionPane.showMessageDialog(null, "deliveryMan Profile Updated");
    }//GEN-LAST:event_updateButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        // customerOp customer = (customerOp) component;
        manageDeliveryMan u = (manageDeliveryMan) component;
        u.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel TitleLab;
    private javax.swing.JLabel addLable1;
    private javax.swing.JTextField addText;
    private javax.swing.JLabel emailLable;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mobileLable;
    private javax.swing.JTextField mobileText;
    private javax.swing.JLabel nameLable;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
