/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Pharmacy.Pharmacy;
import Business.Pharmacy.PharmacyDirectory;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author grees
 */
public class updatePharmacy extends javax.swing.JPanel {

    /**
     * Creates new form updatePharmacy
     */
     private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private PharmacyDirectory pharmacyDirectory;
    private Pharmacy pharmacy;
    public updatePharmacy(JPanel userProcessContainer, EcoSystem ecoSystem, PharmacyDirectory pharmacyDirectory, Pharmacy pharmacy) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.pharmacy = pharmacy;
        this.pharmacyDirectory = ecoSystem.getPharmacyDirectory();
        nameText.setText(pharmacy.getPharmName());
        addText.setText(pharmacy.getAddress());
        mobileText.setText(pharmacy.getPhone());
        emailText.setText(pharmacy.getPharmacist());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        mobileLabel = new javax.swing.JLabel();
        mobileText = new javax.swing.JTextField();
        addLabel = new javax.swing.JLabel();
        addText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 102, 204));
        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Update Pharmacy Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 480, 50));

        updateButton.setBackground(new java.awt.Color(0, 102, 204));
        updateButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Update");
        updateButton.setBorderPainted(false);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 102, 204));
        backButton.setText("<< BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        NameLabel.setBackground(new java.awt.Color(0, 102, 204));
        NameLabel.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(0, 102, 204));
        NameLabel.setText("Pharmacy Name:");
        add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 110, -1));
        add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 180, -1));

        emailLabel.setBackground(new java.awt.Color(0, 102, 204));
        emailLabel.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(0, 102, 204));
        emailLabel.setText("Pharmacist:");
        add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 80, -1));
        add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 180, -1));

        mobileLabel.setBackground(new java.awt.Color(0, 102, 204));
        mobileLabel.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        mobileLabel.setForeground(new java.awt.Color(0, 102, 204));
        mobileLabel.setText("Mobile:");
        add(mobileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 80, -1));
        add(mobileText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 180, -1));

        addLabel.setBackground(new java.awt.Color(0, 102, 204));
        addLabel.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        addLabel.setForeground(new java.awt.Color(0, 102, 204));
        addLabel.setText("Address:");
        add(addLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 80, -1));
        add(addText, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 180, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1710, 990));
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
         String RestName = nameText.getText();
        String address = addText.getText();
        String phone = mobileText.getText();
        String ManName = emailText.getText();
        if(RestName.isEmpty() || ManName.isEmpty() ||
            phone.isEmpty() || address.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fields cannot be left empty");
            return;
        }

        boolean flag ;

        //String phoneNumber = phone;

        if(phone.length() != 10) {
            JOptionPane.showMessageDialog(null, "PhoneNumber must be of 10 digits");
            return;
        }
        flag = phone.matches("^[0-9]+$");
        if(!flag) {
            JOptionPane.showMessageDialog(null, "Phone Number must have digits only");
            return;
        }
        for(Pharmacy res : pharmacyDirectory.getPharmacyDirectory()) {
            if(res.getPhone().equals(phone) && this.pharmacy != res) {
                JOptionPane.showMessageDialog(null, "Phone Number already exists");
                return;
            }
        }

        //String address = txtAddress.getText();

        pharmacy.setPharmName(RestName);
        pharmacy.setPharmacist(ManName);
        pharmacy.setPhone(phone);
        pharmacy.setAddress(address);

        JOptionPane.showMessageDialog(null, "Pharmacy profile Updated");
    }//GEN-LAST:event_updateButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
                 userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        managePharmacy u = (managePharmacy) component;
        u.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel addLabel;
    private javax.swing.JTextField addText;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JTextField mobileText;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
